# -*- coding: utf-8 -*-
"""AirBnB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjuXSzPLBnpsH962lqjCJzWqqT4No-2F
"""

pip install pyspark

import pyspark as sp
from pyspark.sql import SparkSession
import pyspark.sql as py

spark = SparkSession.builder \
    .appName("Air BnB") \
    .getOrCreate()

data_path = '/content/airbnb.csv'

df = spark.read.csv(data_path,header=True,inferSchema=True)

df.show(100)

unique_sessions = df.distinct().count()
print(unique_sessions)

new_df = df.withColumn('device',py.functions.split(df.dim_device_app_combo,'-').getItem(0))

new_df.show()

new_df.groupBy("device").count().show()